language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
matrix:
  include:
    - python: "3.7"
      dist: xenial
      sudo: true
# command to install dependencies
install: "pip install -e .[dev]"
# command to run tests
script: nosetests
